### ISSUE TITLE
 "FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'release\\0.3.4-BETA'"

### ISSUE THREAD

**Issue by coolping** [chianjin/PDFeXpress#2]
你好，我在執行build.py時出現 "FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'release\\0.3.4-BETA'"
懇請您幫我看看，不知道哪邊的操作有誤
以下是我執行的紀錄，十分感謝您的分享^^

//-------------------------------------------------------------------------------------------------------
E:\[SW] EXE_File>git clone https://github.com/chianjin/PDFeXpress.git
Cloning into 'PDFeXpress'...
remote: Enumerating objects: 888, done.
remote: Counting objects: 100% (168/168), done.
remote: Compressing objects: 100% (102/102), done.
remote: Total 888 (delta 95), reused 131 (delta 66), pack-reused 720
Receiving objects: 100% (888/888), 457.51 KiB | 1.94 MiB/s, done.
Resolving deltas: 100% (620/620), done.

E:\[SW] EXE_File>cd PDFeXpress

E:\[SW] EXE_File\PDFeXpress>python3 C:\Users\jiapinglin\AppData\Local\Programs\Python\Python38\Tools\i18n\msgfmt.py locale\zh_CN\LC_MESSAGES\PDFeXpress.po
[Errno 2] No such file or directory: 'locale\\zh_CN\\LC_MESSAGES\\PDFeXpress.po'

E:\[SW] EXE_File\PDFeXpress>cd src

E:\[SW] EXE_File\PDFeXpress\src>python3 C:\Users\jiapinglin\AppData\Local\Programs\Python\Python38\Tools\i18n\msgfmt.py locale\zh_CN\LC_MESSAGES\PDFeXpress.po

E:\[SW] EXE_File\PDFeXpress\src>python3 build.py
python3: can't open file 'build.py': [Errno 2] No such file or directory

E:\[SW] EXE_File\PDFeXpress\src>cd ..

E:\[SW] EXE_File\PDFeXpress>python3 build.py
Traceback (most recent call last):
  File "build.py", line 19, in <module>
    RELEASE_DIR.mkdir()
  File "C:\Users\jiapinglin\AppData\Local\Programs\Python\Python38\lib\pathlib.py", line 1288, in mkdir
    self._accessor.mkdir(self, mode)
FileNotFoundError: [WinError 3] 系統找不到指定的路徑。: 'release\\0.3.4-BETA'

**Comment by coolping** [comment]
認真看code後已解決XD
